### ISSUE TITLE
Zero batch size after STFT layers

### ISSUE THREAD

**Issue by mo-seph** [keunwoochoi/kapre#116]
This may well not be kapre's fault, but I'm getting the following when training a model: ```tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [0,219] vs. [64,219]
	 [[node sub (defined at /Dropbox/University/Work/Creative Computing/SynthLearn/inver-synth/models/app.py:327) ]] [Op:__inference_train_function_1715]```
 The shapes all look fine:
```
________________________________________________________________________________
Layer (type)              Output Shape              Param #
================================================================================
input (InputLayer)        [(None, 1, 16384)]        0
________________________________________________________________________________
permute (Permute)         (None, 16384, 1)          0
________________________________________________________________________________
stft (STFT)               (None, 61, 257, 1)        0
________________________________________________________________________________
magnitude (Magnitude)     (None, 61, 257, 1)        0
________________________________________________________________________________
magnitude_to_decibel (Mag (None, 61, 257, 1)        0
________________________________________________________________________________
conv2d (Conv2D)           (None, 30, 128, 32)       320
________________________________________________________________________________
conv2d_1 (Conv2D)         (None, 14, 63, 71)        20519
________________________________________________________________________________
conv2d_2 (Conv2D)         (None, 6, 20, 128)        109184
________________________________________________________________________________
conv2d_3 (Conv2D)         (None, 2, 9, 128)         147584
________________________________________________________________________________
conv2d_4 (Conv2D)         (None, 1, 5, 128)         16512
________________________________________________________________________________
conv2d_5 (Conv2D)         (None, 1, 3, 128)         16512
________________________________________________________________________________
flatten (Flatten)         (None, 384)               0
________________________________________________________________________________
dense (Dense)             (None, 512)               197120
________________________________________________________________________________
predictions (Dense)       (None, 219)               112347
================================================================================
```

In the past it complained about having a Permute before the STFT layer, and wanted only Input layers, but this seems to be OK at the moment.

Another model, with an architecture that replaces the STFT with a stack of trainable layers works fine in the same framework:
```
Layer (type)              Output Shape              Param #
================================================================================
raw_audio (InputLayer)    [(None, 16384, 1)]        0
________________________________________________________________________________
conv1d (Conv1D)           (None, 4081, 96)          6240
________________________________________________________________________________
conv1d_1 (Conv1D)         (None, 1013, 96)          295008
________________________________________________________________________________
conv1d_2 (Conv1D)         (None, 250, 128)          196736
________________________________________________________________________________
conv1d_3 (Conv1D)         (None, 61, 257)           263425
________________________________________________________________________________
reshape (Reshape)         (None, 61, 257, 1)        0
________________________________________________________________________________
conv2d (Conv2D)           (None, 30, 128, 32)       320
________________________________________________________________________________
conv2d_1 (Conv2D)         (None, 14, 63, 71)        20519
________________________________________________________________________________
conv2d_2 (Conv2D)         (None, 6, 20, 128)        109184
________________________________________________________________________________
conv2d_3 (Conv2D)         (None, 2, 9, 128)         147584
________________________________________________________________________________
conv2d_4 (Conv2D)         (None, 1, 5, 128)         16512
________________________________________________________________________________
conv2d_5 (Conv2D)         (None, 1, 3, 128)         16512
________________________________________________________________________________
flatten (Flatten)         (None, 384)               0
________________________________________________________________________________
dense (Dense)             (None, 512)               197120
________________________________________________________________________________
predictions (Dense)       (None, 219)               112347
================================================================================
```

Full stacktrace:
```
Traceback (most recent call last):
  File "/Users/dmurrayrust/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/dmurrayrust/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dmurrayrust/Dropbox/University/Work/Creative Computing/SynthLearn/inver-synth/models/spectrogram_cnn.py", line 142, in <module>
    train_model(model_callback=get_model, **setup)
  File "/Users/dmurrayrust/Dropbox/University/Work/Creative Computing/SynthLearn/inver-synth/models/app.py", line 327, in train_model
    history = model.fit(x=training_generator,
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/Users/dmurrayrust/.virtualenvs/inver-synth/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [0,219] vs. [64,219]
	 [[node sub (defined at /Dropbox/University/Work/Creative Computing/SynthLearn/inver-synth/models/app.py:327) ]] [Op:__inference_train_function_1715]

Function call stack:
train_function
```

**Comment by keunwoochoi** [comment]
Hi,

> `tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [0,219] vs. [64,219]`

The errors seem like a shape mismatch between expected target vector and the provided target vector. Was your batch sie 64?

> In the past it complained about having a Permute before the STFT layer, and wanted only Input layers, but this seems to be OK at the moment.

I don't know why there was an error about it but it doesn't like anything to do with Kapre. Kapre layers wouldn't know what was the type of the previous layer.

**Comment by keunwoochoi** [comment]
Can you maybe share the source code that builds the model?
