### ISSUE TITLE
Tensorflow 2.0

### ISSUE THREAD

**Issue by leonardltk** [keunwoochoi/kapre#52]
Any plans for integrating it for tensorflow-2.0 ?

Currently here's an issue i faced when using kapre with tf 2.0

```
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
>>> import os,sys,pdb
>>> import tensorflow as tf
>>> print(tf.__version__)
2.0.0-alpha0
>>> print(tf.keras.__version__)
2.2.4-tf
>>> from tensorflow.keras.models import Sequential
>>> from kapre.time_frequency import Melspectrogram
Using TensorFlow backend.
>>> from kapre.utils import Normalization2D
>>> from kapre.augmentation import AdditiveNoise
>>> input_shape = (6, 44100)
>>> sr = 44100
>>> model = Sequential()
>>> model.add(Melspectrogram(n_dft=512, n_hop=256, input_shape=input_shape,
...                          padding='same', sr=sr, n_mels=128,
...                          fmin=0.0, fmax=sr/2, power_melgram=1.0,
...                          return_decibel_melgram=False, trainable_fb=False,
...                          trainable_kernel=False,
...                          name='trainable_stft'))
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "C:\Users\.conda\envs\Python36_tf2_kapre\lib\site-packages\tensorflow\python\training\tracking\base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\.conda\envs\Python36_tf2_kapre\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 152, in add
    'Found: ' + str(layer))
TypeError: The added layer must be an instance of class Layer. Found: <kapre.time_frequency.Melspectrogram object at 0x000001FD56DA69E8>

```

**Comment by keunwoochoi** [comment]
Hi, I don't think I could prioritize this. I'd love to get a PR :)

**Comment by keunwoochoi** [comment]
#58 fixed it!
